// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jobxlpqfxwbaopjlgadg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvYnhscHFmeHdiYW9wamxnYWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzk1NjYsImV4cCI6MjA1OTk1NTU2Nn0.ooRiBFvG5yKFX9VaZkhRw-TLcIB16DKHtBlodaeV8yU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);